### ISSUE TITLE
A question about error handling

### ISSUE THREAD

**Issue by p-himik** [lovrosdu/klor#1]
Hello. I just finished watching the recording of your presentation at HoC24 (great stuff!), skimming through the docs, and searching the repo, and I cannot find an answer on how to properly handle errors.

Specifically:
1. How to handle in-code errors?
2. How to handle network errors of the "not available" type (the server is down, the network is down)?
3. How to handle network errors of the "takes too long" type (so, need to be able to specify a timeout when a server is overloaded or something else is going on)?

**Comment by lovrosdu** [comment]
Hi, thanks for the interest! That's a really good question. Error handling is unfortunately an area that is still largely unexplored, both in Klor and in choreographic programming in general.

Regarding (1), errors communicated via the standard return value mechanism can of course be handled with choreographic or local conditionals as usual. Exceptions however are not as straightforward and can easily lead to the roles' control flows falling out of sync if unhandled. While Klor does support `try` for exception handling, this operator doesn't have fully choreographic semantics. Its body must be "[homogeneous](https://github.com/lovrosdu/klor/blob/master/doc/reference-01-language.md#other-clojure-operators)", which makes it hard to deal with exceptions that are thrown at one role but influence the behavior of the choreography as a whole. A possible way out would be to transform each exception-throwing function into one that instead returns a special error return value that can then be handled as usual, but this might not be satisfactory or feasible given how widespread exceptions are.

Regarding (2) and (3), depending on the situation, some network errors could be handled at the [transport](https://github.com/lovrosdu/klor/blob/master/doc/reference-02-runtime.md#invoking-projections) layer (the send and receive functions). For example, the transport could transparently retry a communication if it fails or could again return a special error return value that the choreography could check for. It could also give up by potentially throwing an exception and letting it propagate through the projection to the outside, where it could be handled by the "driver code" (i.e. whatever invoked the projection). A separate mechanism for notifying the other roles of an error might be necessary if you would want to e.g., shut down the whole choreography in the case of an error at one of the roles.

One customization point I can envision would be the ability to provide an arbitrary set of options to each communication, perhaps given as extra key-value arguments to the `copy`/`=>` operator. These would then be passed down to the underlying send and receive functions, allowing you to influence the specific communication (e.g., how many times to retry, how long to wait, what to return on error, etc.). However, one might want the transport mechanisms to remain pluggable and for a choreography to be decoupled from a particular transport. It remains unclear how to do this elegantly and whether it's possible or even desirable in general.

I'm happy to answer any other questions you might have. :-)

**Comment by p-himik** [comment]
Thank you!
